[package]
name = "pyroscope"
description = """
Pyroscope Profiler
"""
keywords = ["pyroscope", "profiler"]
authors = ["Abid Omar <contact@omarabid.com>"]
version = "0.4.0"
edition = "2021"
license = "Apache-2.0"
homepage = "https://pyroscope.io"
documentation  = "https://docs.rs/pyroscope"
repository = "https://github.com/pyroscope-io/pyroscope-rs"
readme = "README.md"
autobins = false
autoexamples = false
autotests = false
autobenches = false

[lib]
name = "pyroscope_ffi"
crate-type = ["cdylib"]

[workspace]
members = [
    "pyroscope_backends"
]
exclude = [
    "pyroscope_cli"
]

[[bin]]
name = "pyroscope-cli"
path = "pyroscope_cli/src/main.rs"

[dependencies]
pyroscope_backends = {path = "pyroscope_backends"}
thiserror ="1.0"
log = "0.4"
reqwest = { version = "0.11", features = ["blocking"]}
pprof = "0.6.2"
libc = "^0.2.66"
lazy_static = "1.4.0"

[dev-dependencies]
tokio = { version = "1.13", features = ["full"] }
pretty_env_logger = "0.4.0"

[profile.dev]
opt-level=0
debug = true
rpath = false
lto = false
debug-assertions = true
codegen-units = 4

[profile.release]
opt-level=3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1

[profile.test]
opt-level = 1
debug = true
rpath = false
lto = false
debug-assertions = true
codegen-units = 4

[profile.bench]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
