[package]
name = "pyroscope"
description = """
Pyroscope Profiler
"""
keywords = ["pyroscope", "profiler"]
authors = ["Abid Omar <contact@omarabid.com>"]
version = "0.0.1-alpha"
edition = "2021"
license = "Apache-2.0"
homepage = "https://pyroscope.io"
documentation  = "https://pyroscope.io/docs/"
repository = "https://github.com/omarabid/pyroscope.git"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror ="1.0"
tokio = {version = "1.13", features = ["macros", "sync", "rt-multi-thread"]}
reqwest = {version = "0.11",  default-features = false}
pprof = { git = "https://github.com/omarabid/pprof-rs", branch="support-pyroscope"}
#pprof = "0.6.0"
#pprof = { git = "https://github.com/tikv/pprof-rs.git", branch = "master" }
libc = "^0.2.66"

[dev-dependencies]
tokio = { version = "1.13", features = ["full"] }

[profile.dev]
opt-level=0
debug = true
rpath = false
lto = false
debug-assertions = true
codegen-units = 4

[profile.release]
opt-level=3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1

[profile.test]
opt-level = 1
debug = true
rpath = false
lto = false
debug-assertions = true
codegen-units = 4

[profile.bench]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
