[package]
name = "pyroscope"
description = "Pyroscope Profiler"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
homepage = "https://pyroscope.io"
documentation  = "https://pyroscope.io/docs/"
repository = "https://github.com/omarabid/pyroscope.git"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
