[package]
name = "pyroscope_rbspy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rbspy = "0.11.1"
pyroscope = { path = "../../" }
thiserror ="1.0"
log = "0.4"
anyhow = "*"
