[package]
name = "ffikit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
interprocess = "1.1.1"
pyroscope = "0.5.3"
bincode = "2.0.0-rc.1"
