[package]
name = "core"
version = "0.4.0"
authors = ["Abid Omar <contact@omarabid.com>"]
description = "Core package for the project"
edition = "2021"

[dependencies]
utils = { path = "../utils" }
pyroscope = { path = "../../" }
log = "0.4.14"
