detect_subprocesses = false 
log_level = "info"
no_logging = false
rbspy_blocking = false
pyspy_blocking = false
pyspy_idle = false
pyspy_gil = false
pyspy_native = false
sample_rate = 100
server_address = "http://localhost:4040"
debug = false
