[package]
name = "ffi_lib"
version = "0.1.0"
edition = "2021"

[lib]
name = "pyroscope_ffi"
crate-type = ["dylib"]

[dependencies]
rutie = "0.8.3"
pyroscope = {version = "0.5" }
pyroscope_rbspy = { version = "0.2" }
