[package]
name = "rbspy"
version = "0.1.0"
edition = "2021"

[lib]
name = "rbspy"
crate-type = ["cdylib"]

[dependencies]
pyroscope = {version = "0.5.2" }
pyroscope_rbspy = { version = "0.2" }

[patch.crates-io]
read-process-memory = {git = "https://github.com/omarabid/read-process-memory.git", branch = "0.1.4-fix"}
